updated endpoints
Dexter-s-Laboratory/Superbox pull request #29
Opened 2023-08-02 18:17 UTC by mexicanpepe

Not sure if this is how the endpoints should look like?

2023-08-02 18:41 UTC, pnilan requested changes

2023-08-02 18:41 UTC, pnilan commented on features/LoginSignup/Signin.js
> +      const endpoint = '/api/';
/api/u/users for creating a user, refer to Ahu's nginx host for baseUrl

2023-08-02 18:41 UTC, pnilan commented on features/LoginSignup/Signin.js
> +    const backendResponse = await axios.get('/api/', config);
GET /api/u/users/:user_id

2023-08-02 19:02 UTC, pnilan requested changes
Should be HTTP, also there's a forward slash before the URL, also I would recommend referencing a baseURL variable for the IP since the IP will change every time the nginx VM is rebooted

2023-08-03 18:40 UTC, trilly-con-queso approved these changes
lgtm

2023-08-03 19:29 UTC, pnilan commented
Merging this

2023-08-03 19:29 UTC, merged